version: '3.4'

services:
  scholar-sync-local:
    container_name: otlplus-scholar-sync-nest-local
    platform: linux/amd64
    env_file:
      - ../../../env/.env.local
    environment:
      - NODE_ENV=local
      - DOCKER_DEPLOY=true
    build:
      context: ../../..
      dockerfile: ./deploy/scholar-sync/docker/Dockerfile.server
    image: otlplus-scholar-sync-nest-local
    restart: always
    tty: true
    ports:
      - '9000:9000'
    expose:
      - '9000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '../../../apps/scholar-sync/logs:/var/www/otlplus/apps/scholar-sync/logs'
    working_dir: /var/www/otlplus/
    command: node dist/apps/scholar-sync/apps/scholar-sync/src/bootstrap/bootstrap.js
