export * from './ICourseV2'
export * from './IDepartmentV2'
export * from './ILectureV2'
export * from './IProfessorV2'
export * from './IReviewV2'
export * from './ITimetableV2'
export * from './IUserV2'
