version: '3.4'

services:
  back:
    container_name: otlplus-server-nest-prod
    platform: linux/amd64
    env_file:
      - apps/server/env/.env.prod
    environment:
      - NODE_ENV=prod
      - DOCKER_DEPLOY=true
    build:
      context: .
      dockerfile: ./deploy/server/docker/Dockerfile.server
    image: otlplus-server-nest-prod
    restart: always
    tty: true
    ports:
      - '58000:8000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
    working_dir: /var/www/otlplus-server/apps/server
    command: pm2-runtime start ecosystem.config.js --only @otl/server-nest  --node-args="max-old-space-size=40920"
