version: '3.4'

services:
  back:
    container_name: otlplus-server-consumer-nest-local
    platform: linux/amd64
    env_file:
      - ../../../env/.env.local
    environment:
      - NODE_ENV=local
      - DOCKER_DEPLOY=true
    build:
      context: ../../..
      dockerfile: ./deploy/server-consumer/docker/Dockerfile.server
    image: otlplus-server-consumer-nest-local
    restart: always
    tty: true
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '../../../apps/server-consumer/logs:/var/www/otlplus-server-consumer/logs'
    working_dir: /var/www/otlplus-server-consumer
    command: pm2-runtime start ecosystem.config.js --only @otl/server-consumer-nest  --node-args="max-old-space-size=40920"
#    command: node dist/apps/server/apps/server/src/bootstrap/bootstrap.js
