FROM node:20 AS build

RUN mkdir -p /var/www/otlplus-server-consumer
RUN mkdir -p /var/www/otlplus-server-consumer/libs
RUN mkdir -p /var/www/otlplus-server-consumer/apps
WORKDIR /var/www/otlplus-server-consumer
RUN mkdir -p /var/www/otlplus-server-consumer/apps/server-consumer/logs


COPY package.json yarn.lock* package-lock.json* tsconfig.json tsconfig.build.json ./
# COPY .sentryclirc ./
COPY nest-cli.json ./
COPY ./apps/server-consumer/src/ecosystem.config.js ./

RUN yarn --production

COPY ./apps/server ./apps/server
COPY ./apps/scholar-sync ./apps/scholar-sync
COPY ./apps/server-consumer ./apps/server-consumer
COPY ./apps/notification-consumer ./apps/notification-consumer
COPY ./libs/common ./libs/common
COPY ./libs/prisma-client ./libs/prisma-client
COPY ./libs/rmq ./libs/rmq


RUN yarn client:generate
RUN yarn build:server-consumer

FROM node:20-slim AS server
RUN apt-get update -y && apt-get install -y openssl

COPY --from=build /var/www/otlplus-server-consumer/dist/apps/server-consumer /var/www/otlplus-server-consumer/dist/apps/server-consumer
COPY --from=build /var/www/otlplus-server-consumer/node_modules /var/www/otlplus-server-consumer/node_modules
COPY --from=build /var/www/otlplus-server-consumer/ecosystem.config.js /var/www/otlplus-server-consumer/ecosystem.config.js

RUN yarn global add pm2

# RUN pm2 install pm2-metrics

WORKDIR /var/www/otlplus-server-consumer

EXPOSE 3000