FROM node:18

ENV NODE_ENV=dev

RUN mkdir -p /var/www/otlplus-server
WORKDIR /var/www/otlplus-server

COPY package*.json ./
RUN npm install --force

COPY . .
RUN npm run client:generate
RUN npm run build

EXPOSE 8000
CMD [ "npm", "run", "start:dev" ]
