version: '3.4'

services:
  db:
    container_name: otlplus-server-db
    image: mysql:8.0.36
    restart: on-failure
    ports:
      - '${OTLPLUS_DB_PORT:-43306}:3306'
    environment:
      - MYSQL_ROOT_HOSTS=admin
      - MYSQL_ROOT_PASSWORD=${OTLPLUS_DB_PASSWORD:-password}
      - MYSQL_DATABASE=otlplus
      - TZ=Asia/Seoul
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/dump
    command: |
      --sql_mode=NO_ENGINE_SUBSTITUTION --default_storage_engine=InnoDB 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
