version: '3.4'

services:
  back:
    container_name: otlplus-server-nest-dev
    platform: linux/amd64
    env_file:
      - ../env/.env.dev
    environment:
      - NODE_ENV=dev
      - DOCKER_DEPLOY=true
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.server
    image: otlplus-server-nest-dev
    restart: always
    tty: true
    ports:
      - '8080:8000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
    working_dir: /var/www/otlplus-server
    command: node dist/src/bootstrap/bootstrap.js
