version: '3'

networks:
  app_net:
    name: docker_default
    external: true

services:
  rabbitmq:
    build:
      dockerfile: Dockerfile
    container_name: delayed-rabbitmq
    ports:
      - '5672:5672' # AMQP 프로토콜 (앱들이 사용하는 포트)
      - '15672:15672' # 관리 콘솔 (웹 UI) 포트
    env_file: '../../env/.env.dev'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app_net
    restart: unless-stopped
