version: '3.4'

services:
  redis-cache:
    image: redis:7.2-alpine
    container_name: redis-otl
    expose:
      - '6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
  back:
    container_name: otlplus-server-nest-dev
    platform: linux/amd64
    depends_on:
      - redis-cache
    env_file:
      - ../../../env/.env.dev
    environment:
      - NODE_ENV=dev
      - DOCKER_DEPLOY=true
    build:
      context: ../../..
      dockerfile: ./deploy/server/docker/Dockerfile.server
    image: otlplus-server-nest-dev
    restart: always
    tty: true
    ports:
      - '8000:8000'
    expose:
      - '8000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - './apps/server/logs:/var/www/otlplus-server/apps/server/logs'
    working_dir: /var/www/otlplus-server
    command: pm2-runtime start ecosystem.config.js --only @otl/server-nest  --node-args="max-old-space-size=40920"
