version: '3.4'

services:
  back:
    container_name: otlplus-server-nest-dev
    platform: linux/amd64
    env_file:
      - ../../../env/.env.dev
    environment:
      - NODE_ENV=dev
      - DOCKER_DEPLOY=true
    build:
      context: ../../..
      dockerfile: ./deploy/server/docker/Dockerfile.server
    image: otlplus-server-nest-dev
    restart: always
    tty: true
    ports:
      - '8000:8000'
    expose:
      - '8000'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - './apps/server/logs:/var/www/otlplus-server/apps/server/logs'
    working_dir: /var/www/otlplus-server
    command: pm2-runtime start ecosystem.config.js --only @otl/server-nest  --node-args="max-old-space-size=40920"
