version: '3.4'

services:
  db:
    container_name: otlplus-server-db
    image: postgres:18
    restart: on-failure
    ports:
      - '${OTLPLUS_DB_PORT:-45432}:5432'
    environment:
      - POSTGRES_USER=${OTLPLUS_DB_USER:-otlplus}
      - POSTGRES_PASSWORD=${OTLPLUS_DB_PASSWORD:-password}
      - POSTGRES_DB=otlplus
      - TZ=Asia/Seoul
    volumes:
      - ../../../apps/server/volumes/db:/var/lib/postgresql
      - ../../../apps/server/volumes/dump:/dump
      - ./init-shadow-db.sql:/docker-entrypoint-initdb.d/10-init-shadow-db.sql:ro
