services:
  redis-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-scheduler
    ports:
      - '56379:6379'
    env_file:
      - ../../env/.env.prod
    volumes:
      - ./redis-data:/data
      - ./redis.template.conf:/usr/local/etc/redis/redis.template.conf
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        envsubst < /usr/local/etc/redis/redis.template.conf > /usr/local/etc/redis/redis.conf && \
        redis-server /usr/local/etc/redis/redis.conf
